#For shared directories on windows the path should be like
# path: "\\\\1.2.3.4\\abc\\def\\ProductI

# Make sure the metric prefix ends with a |

#Use this metric prefix when SIM is enabled.
metricPrefix: "Custom Metrics|File Watcher|"

# To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/LATEST/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<Component_ID OR Component_Name>|Custom Metrics|File Watcher|"

# List of files
pathsToProcess:
  # Matching all files and directories within TestFiles, recursively
- displayName: "TestPath1 - Regular"
  path: "src/test/resources/TestFiles/**"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

  #Matching all files and directories within TestFiles, non-recursively
- displayName: "TestPath1 - Single level *"
  path: "src/test/resources/TestFiles/*"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

  #Matching only the configured directory
- displayName: "TestPath1 - Specific Directory"
  path: "src/test/resources/TestFiles"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

  #Matching a specific file
- displayName: "TestPath1 - Specific File"
  path: "src/test/resources/TestFiles/TF1.txt"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

  #Matching a specific file or files that match a file extension regex
- displayName: "TestPath1 - File regex"
  path: "src/test/resources/TestFiles/*.txt"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

  #Matching all file extensions within a directory
- displayName: "TestPath1 - All file extensions"
  path: "src/test/resources/TestFiles/*.*"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

  #Matching a file with a regex in conjunction with a directory with a regex (any of the above can be used with this)
- displayName: "TestPath1 - File and Dir regexes"
  path: "src/test/resources/Test*/*.*"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory


metrics:
   fileSize:
      alias: "File Size (Bytes)"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   oldestFileAge:
      alias: "Oldest File Age"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   fileCount:
      alias: "File Count"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   numberOfLines:
      alias: "Number of Lines"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   lastModifiedTime:
      alias: "Last Modified Time"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   available:
      alias: "Available"
      multiplier:
      delta:
      timeRollupType:
      clusterRollupType:
      convert:
        "true": 1
        "false": 0

  # A metric to view the count of files in a directory and all its subdirectories.
  #Set recursiveFileCounts to true for any configured paths to see this metric. Will only work for directories.
   recursiveFileCount:
      alias: "Recursive File Count"
      multiplier:
      delta:
      timeRollupType:
      clusterRollupType:

numberOfThreads: 20 #One thread per base directory + 1
