# List of files
pathsToProcess:
- displayName: "TestPath1 - Regular"
  path: "/Users/aj89/repos/appdynamics/extensions/AppDynamics-File-Watcher-Extension/src/test/resources/TestFiles/**"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileSizes: false # if set to true, this will provide a file size metric at the configured base directory level and each subdirectory
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

- displayName: "TestPath1 - Single level *"
  path: "/Users/aj89/repos/appdynamics/extensions/AppDynamics-File-Watcher-Extension/src/test/resources/TestFiles/*"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileSizes: false # if set to true, this will provide a file size metric at the configured base directory level and each subdirectory
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

- displayName: "TestPath1 - Fully recursive"
  path: "/Users/aj89/repos/appdynamics/extensions/AppDynamics-File-Watcher-Extension/src/test/resources/TestFiles/**"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileSizes: false # if set to true, this will provide a file size metric at the configured base directory level and each subdirectory
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

- displayName: "TestPath1 - File extensions"
  path: "/Users/aj89/repos/appdynamics/extensions/AppDynamics-File-Watcher-Extension/src/test/resources/TestFiles/*.txt"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileSizes: false # if set to true, this will provide a file size metric at the configured base directory level and each subdirectory
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

- displayName: "TestPath1 - Weird regexes"
  path: "/Users/aj89/repos/appdynamics/extensions/AppDynamics-File-Watcher-Extension/src/test/resources/Test*/*"
  ignoreHiddenFiles: true
  excludeSubdirectoriesFromFileCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileSizes: false # if set to true, this will provide a file size metric at the configured base directory level and each subdirectory
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory


metrics:
   fileSize:
      alias: "File Size (Bytes)"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   oldestFileAge:
      alias: "Oldest File Age"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   fileCount:
      alias: "File Count"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   numberOfLines:
      alias: "Number of Lines"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   lastModifiedTime:
      alias: "Last Modified Time"
      multiplier:
      delta:
      aggregationType:
      timeRollupType:
      clusterRollupType:
   available:
      alias: "Available"
      multiplier:
      delta:
      timeRollupType:
      clusterRollupType:
      convert:
        "true": 1
        "false": 0
   recursiveFileCount:
      alias: "Recursive File Count" # A metric to view the count of files in a directory and all its subdirectories. Set recursiveFileCounts to true for any configured paths to see this metric. Will only work for directories.
      multiplier:
      delta:
      timeRollupType:
      clusterRollupType:


#For the shared directory on windows the path should be like
# path: "\\\\1.2.3.4\\abc\\def\\ProductI

# Make sure the metric prefix ends with a |
# This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
# To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Custom Metrics|FileWatcher|"

numberOfThreads: 20
