# List of files
fileToProcess:

  - displayName: "test1"
    path: "/Users/deepak.kalra/Documents/appdynamics-docs/**"
    ignoreHiddenFiles: false
    isDirectoryDetailsRequired: true

  - displayName: "test2"
    path: "/Users/deepak.kalra/Documents/test/**"
    ignoreHiddenFiles: false
    isDirectoryDetailsRequired: true    


  - displayName: "test3"
    path: "/Users/deepak.kalra/Desktop/https___www.myutiitsl.pdf"
    ignoreHiddenFiles: false
    isDirectoryDetailsRequired: true   
    
    
#For the shared directory on windows the path should be like
# path: "\\\\1.2.3.4\\abc\\def\\ProductI


# If false then all the files under the directory will be ignored and only the directory level metrics will be published
# for the directories specified above.
# For files given above it will have no effect
isDirectoryDetailsRequired: false

# If true then an extra metric will be shown that will give age of the oldest file (in seconds when the file was last
# modified and compared to current time) in the directory specified above.
# For files given above it will not display this metric
isOldestFileAgeMetricRequired: true

# If true then an extra metric will be shown that will give number of files in the directories specified above.
# For files given above it will not display this metric
isFileCountRequired: true

# If true then all the hidden files will be ignored monitoring.
ignoreHiddenFiles: true

# Make sure the metric prefix ends with a |
# This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
# To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|FileWatcher|"

numberOfThreads: 5