# List of files
pathsToProcess:
- displayName: "TestPath"
  path: "/Users/aj89/repos/appdynamics/file-monitoring-extension/src/test/resources/TestFiles/"
  ignoreHiddenFiles: true
  excludeSubdirectoryCount: false #if set to true, this will count only the 'files' under the base directory and exclude subdirectories
  recursiveFileSizes: false # if set to true, this will provide a file size metric at the configured base directory level and each subdirectory
  recursiveFileCounts: false # if set to true, this will provide the total count (recursively) of files within the base directory and each subdirectory

#For the shared directory on windows the path should be like
# path: "\\\\1.2.3.4\\abc\\def\\ProductI

# Make sure the metric prefix ends with a |
# This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
# To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|FileWatcher|"

numberOfThreads: 5
